name: ourwonderfullapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #---------------Geolocation---------------
  geolocator: ^5.3.0
  ##geolocator: ^5.1.4+2
  #google_maps_flutter: ^0.5.11
  #location: ^2.5.0
  #flutter_google_places: ^0.2.4
  #google_maps_webservice: ^0.0.16
  #google_map_polyline:  ^0.2.0+1
  #permission: ^0.1.7
  #--------------- Firebase ---------------
  firebase_auth: 'any'
  cloud_firestore: 'any'
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.3
  cloud_functions: 'any'
  firebase_database: ^3.1.3
  #---------------Input validation-----------
  email_validator: ^1.0.4
  #mobile_number: ^0.0.4
  #international_phone_input: ^1.0.3
  #--------------- Files -----------
  file_picker: ^1.5.0+2
  path_provider: ^1.6.4
  #---------------Widgets-----------
  flutter_typeahead: ^1.8.0
  direct_select: ^1.0.0
  rect_getter: ^0.0.1
  #---------------Others------------
  enum_to_string: ^1.0.9
  #google_api_availability: ^2.0.4
  #flutter_local_notifications: ^1.3.0
  provider: ^4.0.4
  battery: 'any' #0.3.0+4
  #google_sign_in: ^4.4.4
  #flutter_facebook_login: ^3.0.0
  settings_ui: ^0.2.0
  country_pickers: ^1.2.0
  country_currency_pickers: ^1.0.1
  flutter_radio_button_group: ^0.0.2+3
  pin_entry_text_field: ^0.1.3
  pin_code_text_field: ^1.5.1
  pin_input_text_field: ^3.0.1
  otp_text_field: ^1.0.1
  http: '>=0.11.3+12'
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/login.jpg
    - assets/images/logo.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/signup.jpg
    - assets/images/shapeup.png
    - assets/images/shapedown.png
    - assets/images/send.png
    - assets/images/image.png
    - assets/images/shape.png
    - assets/images/texto.png
    - assets/images/groupe.png
    - assets/images/image.png
    - assets/images/shape.png
    - assets/images/profileFemale.png
    - assets/images/profileMale.gif
    - assets/images/mer.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
